import '@/styles/globals.css';
import { Providers } from './providers';

export const metadata = {
  title: 'FloorMates',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-charcoal text-white/[0.87]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
